# Generated by Django 5.2.6 on 2025-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_contactrequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
